server:
  port: 8066
  # Tomcat服务器超时配置
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 60000
    accept-count: 100
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
  mvc:                                    # 注意：mvc 要缩进到 spring 下面
    pathmatch:
      matching-strategy: ant_path_matcher



mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.baomidou.mybatisplus: debug
exa:
  get-item-url: ${exa.host}/exawebapi/exaitem/getitems
  get-values: ${exa.host}/exawebapi/exanow/GetFloatValueBatch